# Generated by Django 3.0.8 on 2020-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_highscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('x_coordinate', models.SmallIntegerField()),
                ('y_coordinate', models.SmallIntegerField()),
            ],
        ),
    ]
